# Generated by Django 4.1.3 on 2023-01-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_order_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
