# Generated by Django 4.1.3 on 2023-01-08 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_remove_order_updated_at_cart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-ordered_date"]},
        ),
        migrations.RenameField(
            model_name="order",
            old_name="created_at",
            new_name="ordered_date",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="ordered",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="ordered_date",
        ),
    ]
