# Generated by Django 4.1.3 on 2023-01-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_order_payment_option_address_order_billing_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_option",
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(default="country ?", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_address",
            field=models.CharField(default="billing_address ", max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(default="shipping_address ", max_length=200),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
