# Generated by Django 4.1.3 on 2023-01-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_remove_order_payment_option_order_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="billing_address",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
